from __future__ import annotations

import base64
import json
import mimetypes
import re
import textwrap
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional, Tuple

from services.common.config import load_settings

PLATE_PATTERN = re.compile(r"^[A-Z]{2}\d{2}[A-Z]{1,3}\d{1,4}$")

GEMINI_SYSTEM_PROMPT = """You are an AI-powered traffic enforcement assistant integrated into an automated footpath violation detection system.

Your task is to analyze a provided vehicle image and structured metadata, then generate a legally formatted, fact-based e-Challan record.

Rules:
- Do not hallucinate unknown details.
- Only use facts visible in the image or provided in metadata.
- If uncertain, mark the field as UNKNOWN.
- Follow Indian traffic challan standards.
- Output valid JSON only.
- Keep descriptions precise, formal, and legally usable.
- Validate Indian registration plates like KA05AB1234.
- Do not generate fictional owner identity or personal data.
"""


def _iso_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _safe_float(value: Any, default: float = 0.0) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def _safe_bool(value: Any) -> Optional[bool]:
    if isinstance(value, bool):
        return value
    return None


def _preferred_evidence(violation: Dict[str, Any]) -> Tuple[Optional[Path], Optional[str]]:
    evidence = violation.get("evidence", {})
    if not isinstance(evidence, dict):
        return None, None

    for key in ("vehicle_highlighted", "annotated_frame", "full_frame", "thumbnail"):
        candidate = evidence.get(key)
        if isinstance(candidate, str) and candidate.strip():
            path = Path(candidate)
            if path.exists():
                return path, key

    return None, None


def _sanitize_plate(plate: Any, confidence: float) -> str:
    if not isinstance(plate, str):
        return "UNKNOWN"

    normalized = "".join(ch for ch in plate.upper() if ch.isalnum())
    if confidence <= 0.75:
        return "UNKNOWN"
    if not PLATE_PATTERN.match(normalized):
        return "UNKNOWN"
    return normalized


def _clip_confidence(value: float) -> float:
    return round(max(0.0, min(1.0, value)), 3)


def _clean_json_text(raw: str) -> str:
    text = raw.strip()
    if text.startswith("```"):
        lines = [line for line in text.splitlines() if not line.startswith("```")]
        text = "\n".join(lines).strip()
    return text


def _pdf_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def _jpeg_dimensions(data: bytes) -> Tuple[int, int, str]:
    if len(data) < 4 or data[:2] != b"\xff\xd8":
        raise ValueError("Only JPEG evidence can be embedded in challan PDF")

    offset = 2
    while offset + 9 < len(data):
        if data[offset] != 0xFF:
            offset += 1
            continue

        marker = data[offset + 1]
        offset += 2

        while marker == 0xFF and offset < len(data):
            marker = data[offset]
            offset += 1

        if marker in (0xD8, 0xD9):
            continue

        if offset + 2 > len(data):
            break

        segment_length = int.from_bytes(data[offset : offset + 2], "big")
        if segment_length < 2:
            break

        if marker in {
            0xC0,
            0xC1,
            0xC2,
            0xC3,
            0xC5,
            0xC6,
            0xC7,
            0xC9,
            0xCA,
            0xCB,
            0xCD,
            0xCE,
            0xCF,
        }:
            if offset + 9 > len(data):
                break
            height = int.from_bytes(data[offset + 3 : offset + 5], "big")
            width = int.from_bytes(data[offset + 5 : offset + 7], "big")
            components = data[offset + 7]
            color_space = "/DeviceGray" if components == 1 else "/DeviceRGB"
            return width, height, color_space

        offset += segment_length

    raise ValueError("Unable to determine JPEG dimensions")


def _write_pdf(
    output_path: Path,
    title: str,
    lines: list[str],
    evidence_image_path: Optional[Path],
) -> None:
    image_bytes = None
    image_width = 0
    image_height = 0
    image_color_space = "/DeviceRGB"

    if evidence_image_path is not None and evidence_image_path.suffix.lower() in {".jpg", ".jpeg"}:
        try:
            image_bytes = evidence_image_path.read_bytes()
            image_width, image_height, image_color_space = _jpeg_dimensions(image_bytes)
        except (OSError, ValueError):
            image_bytes = None

    content_lines: list[str] = []
    y_cursor = 770
    title_lines = [title, "Generated by FootWatch Automated Challan Service"]

    for line in title_lines:
        font_size = 16 if line == title else 10
        content_lines.append(f"BT /F1 {font_size} Tf 50 {y_cursor} Td ({_pdf_escape(line)}) Tj ET")
        y_cursor -= 18

    y_cursor -= 6
    for line in lines:
        for wrapped in textwrap.wrap(line, width=78) or [""]:
            content_lines.append(f"BT /F1 11 Tf 50 {y_cursor} Td ({_pdf_escape(wrapped)}) Tj ET")
            y_cursor -= 15

    if image_bytes is not None:
        max_width = 510
        max_height = 220
        scale = min(max_width / image_width, max_height / image_height, 1.0)
        render_width = round(image_width * scale, 2)
        render_height = round(image_height * scale, 2)
        image_y = 40
        content_lines.append(f"BT /F1 10 Tf 50 {image_y + render_height + 16:.2f} Td (Evidence Image) Tj ET")
        content_lines.append(
            f"q {render_width:.2f} 0 0 {render_height:.2f} 50 {image_y:.2f} cm /Im0 Do Q"
        )

    content_stream = "\n".join(content_lines).encode("utf-8")

    objects: list[bytes] = []
    objects.append(b"<< /Type /Catalog /Pages 2 0 R >>")
    objects.append(b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>")

    resources = "<< /Font << /F1 4 0 R >>"
    image_object_id: Optional[int] = None
    if image_bytes is not None:
        image_object_id = 5
        resources = f"{resources} /XObject << /Im0 {image_object_id} 0 R >>"
    resources = f"{resources} >>"

    content_object_id = 6 if image_object_id is not None else 5
    objects.append(
        (
            f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources {resources} "
            f"/Contents {content_object_id} 0 R >>"
        ).encode("utf-8")
    )
    objects.append(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")

    if image_bytes is not None:
        image_object = (
            f"<< /Type /XObject /Subtype /Image /Width {image_width} /Height {image_height} "
            f"/ColorSpace {image_color_space} /BitsPerComponent 8 /Filter /DCTDecode /Length {len(image_bytes)} >>\n"
            "stream\n"
        ).encode("utf-8") + image_bytes + b"\nendstream"
        objects.append(image_object)

    content_object = (
        f"<< /Length {len(content_stream)} >>\nstream\n".encode("utf-8")
        + content_stream
        + b"\nendstream"
    )
    objects.append(content_object)

    pdf = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for index, obj in enumerate(objects, start=1):
        offsets.append(len(pdf))
        pdf.extend(f"{index} 0 obj\n".encode("utf-8"))
        pdf.extend(obj)
        pdf.extend(b"\nendobj\n")

    xref_offset = len(pdf)
    pdf.extend(f"xref\n0 {len(objects) + 1}\n".encode("utf-8"))
    pdf.extend(b"0000000000 65535 f \n")
    for offset in offsets[1:]:
        pdf.extend(f"{offset:010d} 00000 n \n".encode("utf-8"))

    pdf.extend(
        (
            f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref_offset}\n%%EOF"
        ).encode("utf-8")
    )
    output_path.write_bytes(bytes(pdf))


class ChallanEngine:
    def __init__(self) -> None:
        self._settings = load_settings()
        self._artifacts_dir = self._settings.local_data_dir / "challans"
        self._artifacts_dir.mkdir(parents=True, exist_ok=True)

    def build_for_violation(
        self,
        violation: Dict[str, Any],
        existing_challan: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        now = _iso_now()
        vehicle = violation.get("vehicle", {})
        confidence = _safe_float(vehicle.get("plate_ocr_confidence"))
        evidence_image_path, evidence_image_type = _preferred_evidence(violation)

        if confidence < 0.65:
            return {
                "status": "MANUAL_REVIEW_REQUIRED",
                "download_ready": False,
                "fine_amount_inr": int(violation.get("fine_amount_inr", self._settings.challan_fine_amount_inr)),
                "provider": "manual_review_gate",
                "model": None,
                "generated_at": now,
                "manual_review_reason": "ocr_confidence_below_0_65",
                "evidence_image_type": evidence_image_type,
                "evidence_image_path": str(evidence_image_path) if evidence_image_path else None,
                "semantic_record": None,
                "pdf_path": None,
                "json_path": None,
                "generation_error": None,
            }

        if evidence_image_path is None:
            return {
                "status": "PENDING_EVIDENCE",
                "download_ready": False,
                "fine_amount_inr": int(violation.get("fine_amount_inr", self._settings.challan_fine_amount_inr)),
                "provider": "pending_evidence",
                "model": None,
                "generated_at": now,
                "manual_review_reason": None,
                "evidence_image_type": None,
                "evidence_image_path": None,
                "semantic_record": None,
                "pdf_path": None,
                "json_path": None,
                "generation_error": None,
            }

        existing_path = existing_challan.get("pdf_path") if isinstance(existing_challan, dict) else None
        if (
            isinstance(existing_challan, dict)
            and existing_challan.get("status") in {"READY", "READY_FALLBACK"}
            and existing_challan.get("evidence_image_path") == str(evidence_image_path)
            and isinstance(existing_path, str)
            and Path(existing_path).exists()
        ):
            return existing_challan

        semantic_record = None
        provider = "fallback"
        model = None
        generation_error = None

        if self._settings.gemini_api_key:
            try:
                semantic_record = self._call_gemini(violation=violation, evidence_image_path=evidence_image_path)
                provider = "gemini"
                model = self._settings.gemini_model
            except (OSError, ValueError, urllib.error.URLError) as exc:
                generation_error = str(exc)

        if semantic_record is None:
            semantic_record = self._build_fallback_semantic_record(violation)

        semantic_record = self._coerce_semantic_record(semantic_record, violation)
        json_path, pdf_path = self._write_artifacts(
            violation=violation,
            semantic_record=semantic_record,
            evidence_image_path=evidence_image_path,
        )

        return {
            "status": "READY" if provider == "gemini" else "READY_FALLBACK",
            "download_ready": True,
            "fine_amount_inr": int(violation.get("fine_amount_inr", self._settings.challan_fine_amount_inr)),
            "provider": provider,
            "model": model,
            "generated_at": now,
            "manual_review_reason": None,
            "evidence_image_type": evidence_image_type,
            "evidence_image_path": str(evidence_image_path),
            "semantic_record": semantic_record,
            "pdf_path": str(pdf_path),
            "json_path": str(json_path),
            "generation_error": generation_error,
        }

    def _call_gemini(self, violation: Dict[str, Any], evidence_image_path: Path) -> Dict[str, Any]:
        mime_type, _ = mimetypes.guess_type(evidence_image_path.name)
        mime_type = mime_type or "image/jpeg"
        evidence_bytes = evidence_image_path.read_bytes()
        evidence_base64 = base64.b64encode(evidence_bytes).decode("ascii")

        location = violation.get("location", {})
        vehicle = violation.get("vehicle", {})
        metadata = {
            "timestamp": violation.get("timestamp"),
            "location": location.get("location_name") or "UNKNOWN",
            "gps": [location.get("gps_lat"), location.get("gps_lng")],
            "camera_id": location.get("camera_id"),
            "detected_vehicle_class": vehicle.get("vehicle_class"),
            "estimated_speed_kmph": vehicle.get("estimated_speed_kmph"),
            "ocr_plate_text": vehicle.get("plate_number"),
            "ocr_confidence": vehicle.get("plate_ocr_confidence"),
        }

        request_payload = {
            "contents": [
                {
                    "role": "user",
                    "parts": [
                        {
                            "text": (
                                f"{GEMINI_SYSTEM_PROMPT}\n"
                                "Use the provided image and metadata to produce the strict challan JSON schema.\n"
                                f"Metadata:\n{json.dumps(metadata, ensure_ascii=True)}"
                            )
                        },
                        {
                            "inline_data": {
                                "mime_type": mime_type,
                                "data": evidence_base64,
                            }
                        },
                    ],
                }
            ],
            "generationConfig": {
                "temperature": 0.1,
                "responseMimeType": "application/json",
            },
        }

        url = (
            "https://generativelanguage.googleapis.com/v1beta/models/"
            f"{self._settings.gemini_model}:generateContent?key={self._settings.gemini_api_key}"
        )
        request = urllib.request.Request(
            url=url,
            method="POST",
            headers={"Content-Type": "application/json"},
            data=json.dumps(request_payload).encode("utf-8"),
        )

        with urllib.request.urlopen(request, timeout=20) as response:
            response_payload = json.loads(response.read().decode("utf-8"))

        candidates = response_payload.get("candidates") or []
        if not candidates:
            raise ValueError("Gemini did not return any candidates")

        parts = candidates[0].get("content", {}).get("parts") or []
        if not parts or not isinstance(parts[0].get("text"), str):
            raise ValueError("Gemini response did not contain JSON text")

        raw_text = _clean_json_text(parts[0]["text"])
        return json.loads(raw_text)

    def _build_fallback_semantic_record(self, violation: Dict[str, Any]) -> Dict[str, Any]:
        location = violation.get("location", {})
        vehicle = violation.get("vehicle", {})
        confidence = _clip_confidence(_safe_float(vehicle.get("plate_ocr_confidence")))
        plate_number = _sanitize_plate(vehicle.get("plate_number"), confidence)

        return {
            "violation_confirmed": True,
            "vehicle_details": {
                "vehicle_type": vehicle.get("vehicle_class") or "UNKNOWN",
                "vehicle_color": vehicle.get("vehicle_color") or "UNKNOWN",
                "vehicle_description": vehicle.get("vehicle_description") or "UNKNOWN",
                "license_plate": plate_number,
                "plate_confidence": confidence,
            },
            "violation_details": {
                "violation_type": "FOOTPATH ENCROACHMENT",
                "severity": "moderate",
                "speed_kmph": _safe_float(vehicle.get("estimated_speed_kmph")),
                "location": location.get("location_name") or "UNKNOWN",
                "timestamp": violation.get("timestamp") or "UNKNOWN",
            },
            "visual_analysis": {
                "footpath_detected": True,
                "pedestrian_zone": True,
                "rider_present": _safe_bool(violation.get("visual_analysis", {}).get("rider_present")),
                "image_quality": "clear" if confidence >= 0.85 else "usable" if confidence >= 0.75 else "UNKNOWN",
            },
            "legal_summary": (
                "The vehicle bearing registration number "
                f"{plate_number} was observed moving on a designated pedestrian footpath at "
                f"approximately {_safe_float(vehicle.get('estimated_speed_kmph')):.1f} km/h, violating traffic regulations. "
                "This constitutes unauthorized encroachment into a pedestrian-only zone."
            ),
            "confidence_scores": {
                "overall_confidence": confidence,
                "vehicle_detection_confidence": _clip_confidence(
                    _safe_float(violation.get("system", {}).get("vehicle_detection_confidence"), confidence)
                ),
                "plate_read_confidence": confidence,
            },
        }

    def _coerce_semantic_record(self, record: Dict[str, Any], violation: Dict[str, Any]) -> Dict[str, Any]:
        fallback = self._build_fallback_semantic_record(violation)
        merged = dict(fallback)

        for section in ("vehicle_details", "violation_details", "visual_analysis", "confidence_scores"):
            merged[section] = dict(fallback[section])
            incoming = record.get(section)
            if isinstance(incoming, dict):
                merged[section].update(incoming)

        merged["violation_confirmed"] = bool(record.get("violation_confirmed", True))
        merged["legal_summary"] = str(record.get("legal_summary") or fallback["legal_summary"])
        merged["vehicle_details"]["license_plate"] = _sanitize_plate(
            merged["vehicle_details"].get("license_plate"),
            _safe_float(merged["vehicle_details"].get("plate_confidence"), _safe_float(
                violation.get("vehicle", {}).get("plate_ocr_confidence")
            )),
        )

        for field in ("plate_confidence",):
            merged["vehicle_details"][field] = _clip_confidence(_safe_float(merged["vehicle_details"].get(field)))

        for field in ("overall_confidence", "vehicle_detection_confidence", "plate_read_confidence"):
            merged["confidence_scores"][field] = _clip_confidence(
                _safe_float(merged["confidence_scores"].get(field))
            )

        merged["violation_details"]["speed_kmph"] = round(
            _safe_float(merged["violation_details"].get("speed_kmph")),
            2,
        )

        return merged

    def _write_artifacts(
        self,
        violation: Dict[str, Any],
        semantic_record: Dict[str, Any],
        evidence_image_path: Path,
    ) -> Tuple[Path, Path]:
        violation_id = str(violation.get("violation_id") or "unknown")
        safe_id = "".join(ch for ch in violation_id if ch.isalnum() or ch in {"-", "_"})
        base_path = self._artifacts_dir / safe_id
        base_path.mkdir(parents=True, exist_ok=True)

        json_path = base_path / "challan.json"
        pdf_path = base_path / "challan.pdf"

        json_path.write_text(json.dumps(semantic_record, indent=2), encoding="utf-8")

        lines = [
            f"Plate Number: {semantic_record['vehicle_details']['license_plate']}",
            f"Vehicle Type: {semantic_record['vehicle_details']['vehicle_type']}",
            f"Color: {semantic_record['vehicle_details']['vehicle_color']}",
            f"Violation: {semantic_record['violation_details']['violation_type']}",
            f"Speed: {semantic_record['violation_details']['speed_kmph']} km/h",
            f"Location: {semantic_record['violation_details']['location']}",
            f"Date & Time: {semantic_record['violation_details']['timestamp']}",
            f"Fine: INR {int(violation.get('fine_amount_inr', self._settings.challan_fine_amount_inr))}",
            "Legal Note: Unauthorized use of pedestrian footpath by motor vehicles is punishable under the MV Act.",
            f"Summary: {semantic_record['legal_summary']}",
        ]
        _write_pdf(pdf_path, self._settings.challan_pdf_title, lines, evidence_image_path)

        return json_path, pdf_path
